### PR TITLE
Minor module things

### PR DESCRIPTION
**Pull request by VelocityRa**

### CODE REVIEW

**Comment by Inori** [comment]
Thanks for you work.
It's better we place all the switches in one specific file, like `LoaderCommon.h` or somehow.
More and more switches seperated in many files will screw things up.
What I usually do is like this:
https://github.com/Inori/GPCS4/blob/master/GPCS4/Graphic/Gve/GveCommon.h

**Comment by VelocityRa** [comment]
Sounds good to me.

Btw I think it's good practice to use `constexpr` constants for switches in C++ (when it's possible) instead of defines, because inactive code still gets parsed and that way it cannot break when refactoring.

**Comment by Inori** [comment]
Well, it has pros and cons.
What I think is that, constexpr add code complexity, one has to keep the condition in mind while reading the followed code. And 
maybe some runtime overhead？not sure.

**Comment by VelocityRa** [comment]
> one has to keep the condition in mind while reading the followed code

Not sure what you mean, it works exactly like defines.
Also Visual Studio and most IDEs should darken the inactive piece of code, just like they do with inactive ifdefs.

> maybe some runtime overhead？not sure

Definitely not, `constexpr` means that it's guaranteed to be compile-time evaluated, so no code will be emitted it it's `false`.

**Pull request merged**
