### PR TITLE
starter code for 5 modules (attempt 2)

### PR DESCRIPTION
**Pull request by wheelmac92**
I messed up the old fork, had to build a new fork and copy the changes over. This adds code to the following modules:
sce_audioout 
sce_errordialog 
sce_msgdialog
sce_systemservice
sce_userservice

### CODE REVIEW

**Comment by mailwl** [comment]
i like your PR. but afraid it contains prortietary sony code

**Comment by wheelmac92** [comment]
Sorry, I'll take that out

**Comment by wheelmac92** [comment]
Let me know if it looks better now @mailwl

**Comment by Inori** [comment]
Well, like I said, implement error codes is not that meaningful, and even worse, I think this will increase the work in the future when we really implement these modules.

If you just want to begin with some starter code, you can commit step by step as you debug your program, these are good examples:
4dd241a2c96db2967f28388b9ec659b88626c780
ae1a4abf3cc142e917fdd17ff025f07c2eb35c78

**Pull request closed without merging**
