### PR TITLE
[SceLibkernel] Add and implement some features

### PR DESCRIPTION
**Pull request by Ykisl**
Add and implement some features in SceLibkernel.

(mostly pthread)

### CODE REVIEW

**Comment by Inori** [comment]
For `scek_pthread_key_create`, there's a problem.
The `destructor` callback function is provided by game, which follows `sysv abi`.
But it will be used by `pthread4w` library which will assume it's a `ms abi` function.
You need to write a wrapper to deal with callbacks passed from games.
see `scec_qsort` for example:
https://github.com/Inori/GPCS4/blob/master/GPCS4/SceModules/SceLibc/sce_libc_stdlib.cpp#L86

**Comment by VelocityRa** [comment]
_Testing Discord integration_

**Comment by mailwl** [comment]
for me, as every ps4 game includes own version of libc, better way to load provided version of libc.prx

**Comment by VelocityRa** [comment]
@mailwl We already load modules from a firmware dump, this PR is about `SceLibKernel` not `SceLibc` (libc link above is just an example).

**Comment by mailwl** [comment]
ah, i see. libkernel should be HLE, for sure

**Comment by Ykisl** [comment]
it seems that all functions without the sce registry are normal FreeBSD kernel functions and return regular error codes

**Comment by Inori** [comment]
Well, there's maybe another problem.
Functions in our emulator use pthread4w's structure defination,
like `scek_pthread_mutex_lock(pthread_mutex_t* mtx)` use `pthread_mutex_t*` as parameter.
But the game will use standard pthread library's structure, the size of the two maybe not same.
Thus may causing problems like overwrite.

**Comment by mailwl** [comment]
this can be solved like this:
```cpp
typedef struct _ScePthreadMutex {
    // original ps4 pthread_mutex_t
    uint64_t pad[4]{}; // <---- need to find out real size
    // emulator addition
    char name[0x20]{0,};
    pthread_mutex_t* pthread_mutex{nullptr}; // <--- from pthread4w
} * ScePthreadMutex;
```
and then use `pthread_mutex` as parameter for functions from **pthread4w**

**Comment by Ykisl** [comment]
> this can be solved like this:
> 
> ```c++
> typedef struct _ScePthreadMutex {
>     // original ps4 pthread_mutex_t
>     uint64_t pad[4]{}; // <---- need to find out real size
>     // emulator addition
>     char name[0x20]{0,};
>     pthread_mutex_t* pthread_mutex{nullptr}; // <--- from pthread4w
> } * ScePthreadMutex;
> ```
> 
> and then use `pthread_mutex` as parameter for functions from **pthread4w**

image

**Comment by Ykisl** [comment]
> Well, there's maybe another problem.
> Functions in our emulator use pthread4w's structure defination,
> like `scek_pthread_mutex_lock(pthread_mutex_t* mtx)` use `pthread_mutex_t*` as parameter.
> But the game will use standard pthread library's structure, the size of the two maybe not same.
> Thus may causing problems like overwrite.

This is a pointer type.

image

**Comment by Inori** [comment]
I know. See my comments here:
https://github.com/Inori/GPCS4/blob/master/GPCS4/SceModules/SceLibkernel/sce_kernel_scepthread.h#L7

**Comment by mailwl** [comment]
well, we create the structures by youself:
```cpp
PS4API int scePthreadMutexInit(ScePthreadMutex* mutex, const ScePthreadMutexattr* attr, const char* name) {
    *mutex = ::new _ScePthreadMutex;
    if (name) {
        ::strncpy((*mutex)->name, name, 0x20);
    }
    (*mutex)->pthread_mutex = ::new pthread_mutex_t;
   ......

PS4API int scePthreadMutexTrylock(ScePthreadMutex* mutex) {
    pthread_mutex_t* m = (*mutex)->pthread_mutex;
    int rc = ::pthread_mutex_trylock(m);
   .....

```

**Comment by Inori** [comment]
`well, we create the structures by youself`
We don't have problems with `scePthread` prefix functions.
What's going wrong is `scek_` functions, and your approach is a workaround, probably better.
What I use priviously is to define a global handle table, like this:
https://github.com/Inori/GPCS4/blob/master/GPCS4/SceModules/SceLibkernel/sce_pthread_common.h#L22
But seems not clever. Orz
Still we need to find out the real size of the structures which the game use.

**Comment by Inori** [comment]
Wow, seems I'm the stupid one. Yes, most of the `pthread_xxxx_t` types are pointer types, just like `sce` ones.

**Comment by Ykisl** [comment]
> Wow, seems I'm the stupid one. Yes, most of the `pthread_xxxx_t` types are pointer types, just like `sce` ones. @Ykisl


these are the same types

**Comment by Ykisl** [comment]
sce functions differ only in errors

**Comment by Inori** [comment]
Yes, fogive me for my foolish.
We only need to take care of the non pointer types, like `pthread_once_t` and `pthread_t`

**Comment by mailwl** [comment]
for scek_ functions it's possible to use same params types, as for scePthread:
```cpp
PS4API int scek_pthread_mutexattr_init(ScePthreadMutexattr* attr) {
    *attr = ::new _ScePthreadMutexattr;
    ....
```

**Pull request merged**
