### PR TITLE
[SceFios] Add not implemented features for Nier

### PR DESCRIPTION
**Pull request by Ykisl**
I added some functions to SceFios2, it seems that Nier uses them

### CODE REVIEW

**Comment by mailwl** [comment]
Fios2 included in every game, better way to load it, but emulating is good, too

**Comment by Inori** [comment]
@Ykisl  OK, thank you.
By the way, I'm not sure if this helps.
But these stub functions can be generated using [GenerateCode.py](https://github.com/Inori/GPCS4/blob/master/Tools/GenerateCode.py) together with a function list file like [this](https://github.com/Inori/GPCS4/blob/master/Tools/import_modules_nier.txt).
Although these're still some manual works, but things will be a little more easier.

@mailwl This module is for file system, I think we may need to emulate almost all of the functions in it after I saw the function names.

**Comment by VelocityRa** [comment]
Fios is pretty huge (at least it is on PSVita).

We might want to load it instead and implement the kernel functions it uses. I have not looked at its imports (we should) but if they are just kernel IO functions like I expect, it should not be hard.

**Comment by mailwl** [comment]
it imports scePthread* and IO functions, i tryed to run functions from sceFios2 by hands with libkernel emulated, works like a charm.
It also imports sceDiskMap, which works native too

**Comment by Inori** [comment]
I didn't see it's imports, but if most of functions of it are implemented using imports other than syscalls/ioctls, then yes, we should load it.

**Comment by mailwl** [comment]
[belf](https://github.com/balika011/belf) shows imports

**Pull request merged**
